### ISSUE TITLE
I don't really understand your point

### ISSUE THREAD

**Issue by tejasraman** [juanpc2018/Macbook-Pro-2013-Early-problems#1]
This model has official support for Catalina. You using dosdude is a problem. Yes, the 2011 models have a broken AMD card, but yours should work without patching. Also, it has HD Graphics 4000, not 3000 
![image](https://user-images.githubusercontent.com/96961804/182037066-33cedfc8-394d-4b0d-ba9d-27de095654a9.jpeg)

This model was supported officially up to Big Sur (I upgraded a 2013 to Big Sur with no patching, no OCLP).

dosdude1 was talking about the broken 2011 models (not 2013).

That GPU never had a widespread issue. You are thinking of the 2011 models with broken AMD cards. You probably have to get your GPU or mobo replaced. OSX 10.11.3 was probably ok because it was set to not use the NVidia by default.

**Comment by juanpc2018** [comment]
#1. i never talked about dosdude catalina patch in the MBP 2013 Early...

#2. when MBP 2013 Early "Dual Graphics" has a Damaged Nvidia 650M, 
https://everymac.com/systems/apple/macbook_pro/index-macbookpro.html
https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.8-15-early-2013-retina-display-specs.html
https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.7-15-early-2013-retina-display-specs.html
https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.4-15-early-2013-retina-display-specs.html

All hell breaks lose. LOL.™
and The Fruit Company knows...
thats why the latest Firmware is designed to select the damaged 650M at boot,

booting several times to OSX Mavericks, the UEFI selects again the Intel HD4000 at boot, 

the HD4000 was a typo will fix that.
thanks.


MBP 2013 Early has a different SSD,
MBP 2013 Late has the same SSD PCIe as Macmini 2014.
MBP 2013 Late  has 750M
https://beetstech.com/blog/apple-proprietary-ssd-ultimate-guide-to-specs-and-upgrades

The proper way to fix this issue is to solder a New 650M chip to the Early Board,
as far as i know, replacing the Early Board with a 2013 Late board
 is Not compatible with the screen & keyboard connectors. 

replacing the 650M and pray the board is Not damaged. "a job for Luis Rossman",
a Damaged 650M could have created damages in the power delivery pwm phase or voltage regulator.

it becomes a dilema,
board repair or replacement is Not cheap.
and its unknown how it will last.
some people make the mistake of upgrading OSX with a Damaged 650M,
and makes the computer useless, also difficult to recover the information.

spending $$ money to repair an old computer becomes a dilema.
some people want to use it without board repair.
and thats where it gets tricky.
because OSX Catalina converted the HFS+ to APFS,
and information cannot be recovered,
unless you buy a external USB3.0 case for older Apple SSD 2012-2013 early from OWC or another.
copy the information to another HFS+ hdd
then delete the APFS, and reinstall OSX ElCapitan 10.13.3 or Linux or Windows.

**Comment by tejasraman** [comment]
You're just ranting.

**Comment by tejasraman** [comment]
@juanpc2018 I don't want to make a scene but...
OSX 10.7 was released over 10 years ago
OpenOffice hasn't had any feature updates in years even if it got an update recently
You seem to have a thought that Apple is plotting against you. Newer OSX installers don't have the expired certificate (until 2029 anyway)
And yes, I was confused when I said Catalina was the minimum for MacPro5,1. It is the minimum for **MacPro7,1**
And OP is probably a paying 365 customer like I am. I fixed it by creating a custom Library Validation patch based on LibraryValidationDisabler by @mologie 

You have some crazy thought that Apple is anti-consumer and have a ton of **ranting** Github repos.
> everything you write is 50% fake.

This is truer about you than me. The 2013 Mac being faulty? Nah, it was the 2011 15" Mac.

And what can you ban me from? I'm so tired of you spreading misleading trash I'll block you.
